---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-eta-app-all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp-eta-appg-all
  template:
    metadata:
      labels:
        app: bankapp-eta-app-all
    spec:
      containers:
        - name: bankapp-eta-app
          image: deepakvarshney5576/bankapp-eta-app:1.0
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-eta-app-all
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: bankapp-eta-app-all
