---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-all
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-all
  template:
    metadata:
      labels:
        app: bank-all
    spec:
      containers:
        - name: bank
          image: deepakvarshney5576/banking-project:1.0
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: bank-all
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: bank-all
